[package]
name = "minipyth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.34.0"
ron = "^0.7.0"
serde = "^1.0.132"
